runAntisenseDesign.py EnumerationResult.csv
antisense_predictor.py AOBase AOBase_542seq_cleaned_modelBuilding_Jan2009_15_21_noOutliers.csv c_a_thermo predict EnumerationResult_clean.csv < input_15_21_100_1000_12.txt
rm EnumerationResult_clean.csv
mergeASO.py EnumerationResult.csv OuTpUt_ReSuLtS.csv



